# -*- coding: utf-8 -*-
"""Classic_ML_meets_NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jxxovLP4bp3xB0wlrL2VMLG366q7Zp64
"""

# 📝 Обоснование принятых решений


 #Модель: Logistic Regression**  Она быстрая, масштабируемая, устойчива к высокой размерности разреженных признаков и легко интерпретируется. Для 19 классов мультиклассовой задачи дает стабильный baseline без риска переобучения при корректной регуляризации.
 #Векторизация: TF-IDF (sublinear_tf=True)  Подавляет вес слишком частых слов, которые не несут тематической нагрузки.
 #Логарифмическое сглаживание (sublinear_tf) снижает влияние повторов в длинных статьях.
 #Предобработка: Stemming + Regex
 #Snowball Stemmer (ru) нормализует морфологию, сокращая словарь и объединяя формы слов.
 #Регулярки удаляют URL, HTML, числа и спецсимволы, не влияющие на рубрикацию. Фильтр len(w)>2 отсекает шумовые предлоги.
 #Оптимизатор: solver='saga' Поддерживает мультиклассовую задачу, эффективно работает с большими разреженными матрицами и параллелится через n_jobs=-1. Быстрее liblinear и стабильнее lbfgs при l2-регуляризации.
 #Гиперпараметры: C=[0.5, 1.0, 2.0], penalty='l2'
 #L2 предотвращает переобучение на редких n-grams.
 #Стратификация сплитов  stratify=y во всех train_test_split гарантирует идентичное распределение классов в train/val/test. Критично для стабильной оценки Macro F1 при естественном смещении рубрик.
 #Baseline: DummyClassifier  Стратегия most_frequent задает нижнюю границу качества.

import kagglehub

# Скачивание последней версии датасета
path = kagglehub.dataset_download("yutkin/corpus-of-russian-news-articles-from-lenta")
print(" Путь к файлам:", path)

# Установка только необходимых библиотек
!pip install -q kagglehub nltk scikit-learn pandas numpy
print(" Библиотеки установлены.")

import os
import re
import warnings
import numpy as np
import pandas as pd

from nltk.stem.snowball import SnowballStemmer
from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.dummy import DummyClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, classification_report

# Фиксация случайности
SEED = 42
os.environ['PYTHONHASHSEED'] = str(SEED)
np.random.seed(SEED)
warnings.filterwarnings('ignore')

print(" Импорты выполнены, seed зафиксирован.")

# Автоматический поиск CSV в скачанной директории
dataset_path = path
files = os.listdir(dataset_path)
csv_file = next((f for f in files if f.endswith('.csv')), None)

if not csv_file:
    raise FileNotFoundError("CSV файл не найден в директории датасета.")

print(f" Загрузка: {csv_file}")
df = pd.read_csv(os.path.join(dataset_path, csv_file))

# Приведение колонок к стандартным именам
col_map = {}
for c in df.columns:
    cl = c.lower().strip()
    if 'title' in cl: col_map[c] = 'title'
    elif 'text' in cl or 'body' in cl: col_map[c] = 'text'
    elif 'topic' in cl or 'rubric' in cl or 'category' in cl: col_map[c] = 'topic'

df.rename(columns=col_map, inplace=True)
df = df[['title', 'text', 'topic']].dropna()

# Очистка топиков от пустых значений
df['topic'] = df['topic'].astype(str).str.strip()
df = df[df['topic'].isin(['', 'nan', 'None']) == False]

# Объединение заголовка и текста
df['full_text'] = df['title'] + ' ' + df['text']

# Фильтрация редких классов
min_class_size = 50
df = df.groupby('topic').filter(lambda x: len(x) >= min_class_size).reset_index(drop=True)

print(f" Записей после фильтрации: {len(df):,} | Уникальных топиков: {df['topic'].nunique()}")
print(" Топ-5 топиков:\n", df['topic'].value_counts().head())

SAMPLE_SIZE = 100_000

if len(df) > SAMPLE_SIZE:
    df_sampled, _ = train_test_split(df, train_size=SAMPLE_SIZE, stratify=df['topic'], random_state=SEED)
else:
    df_sampled = df.copy()

# Компиляция регексов и стеммер
RE_NOISE = re.compile(r'http\S+|www\S+|https\S+|<.*?>|\d+|[^\w\s]')
RE_SPACE = re.compile(r'\s+')
stemmer = SnowballStemmer("russian")

def preprocess_text(text: str) -> str:
    text = text.lower()
    text = RE_NOISE.sub(' ', text)
    text = RE_SPACE.sub(' ', text).strip()
    return ' '.join(stemmer.stem(w) for w in text.split() if len(w) > 2)

print(" Предобработка текста...")
df_sampled['clean_text'] = df_sampled['full_text'].apply(preprocess_text)

# Кодирование меток
le = LabelEncoder()
df_sampled['target'] = le.fit_transform(df_sampled['topic'])

# Сплит 60/20/20
X = df_sampled['clean_text']
y = df_sampled['target']

X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=SEED)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.25, stratify=y_train_val, random_state=SEED)

print(f" Train: {len(X_train):,} | Val: {len(X_val):,} | Test: {len(X_test):,}")

dummy = DummyClassifier(strategy='most_frequent', random_state=SEED)
dummy.fit(X_train, y_train)
y_pred_dummy = dummy.predict(X_val)

print(" Dummy Baseline (most_frequent):")
print(f"   Accuracy : {accuracy_score(y_val, y_pred_dummy):.4f}")
print(f"   Macro F1 : {f1_score(y_val, y_pred_dummy, average='macro'):.4f}")

pipe_count = Pipeline([
    ('vec', CountVectorizer(max_features=50000, min_df=5, max_df=0.95, ngram_range=(1, 2))),
    ('clf', LogisticRegression(max_iter=1000, solver='saga', n_jobs=-1, random_state=SEED))
])

pipe_tfidf = Pipeline([
    ('vec', TfidfVectorizer(max_features=50000, min_df=5, max_df=0.95, ngram_range=(1, 2), sublinear_tf=True)),
    ('clf', LogisticRegression(max_iter=1000, solver='saga', n_jobs=-1, random_state=SEED))
])

print(" Обучение CountVectorizer + LogReg...")
pipe_count.fit(X_train, y_train)
pred_count = pipe_count.predict(X_val)
print(f" CountVec  | Acc: {accuracy_score(y_val, pred_count):.4f} | Macro F1: {f1_score(y_val, pred_count, average='macro'):.4f}")

print(" Обучение TfidfVectorizer + LogReg...")
pipe_tfidf.fit(X_train, y_train)
pred_tfidf = pipe_tfidf.predict(X_val)
print(f" TfidfVec  | Acc: {accuracy_score(y_val, pred_tfidf):.4f} | Macro F1: {f1_score(y_val, pred_tfidf, average='macro'):.4f}")

param_grid = {
    'vec__max_features': [30000, 50000],
    'vec__ngram_range': [(1, 1), (1, 2)],
    'vec__min_df': [3, 5],
    'clf__C': [0.5, 1.0, 2.0],
    'clf__penalty': ['l2']
}

cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=SEED)
grid = GridSearchCV(pipe_tfidf, param_grid, cv=cv, scoring='f1_macro', n_jobs=-1, verbose=1, refit=True)

print(" Запуск GridSearchCV (3-fold, 24 комбинации)...")
grid.fit(X_train, y_train)

print(f"\n Best Params: {grid.best_params_}")
print(f" Best CV Macro F1: {grid.best_score_:.4f}")

best_model = grid.best_estimator_
y_pred_test = best_model.predict(X_test)

test_acc = accuracy_score(y_test, y_pred_test)
test_f1 = f1_score(y_test, y_pred_test, average='macro')

print("📊 Итоговое качество на TEST выборке:")
print(f"   Accuracy : {test_acc:.4f}")
print(f"   Macro F1 : {test_f1:.4f}\n")

print("📋 Classification Report (топ-10 классов по support):")
report = classification_report(y_test, y_pred_test, target_names=le.classes_, output_dict=True)
df_report = pd.DataFrame(report).transpose()
print(df_report.sort_values('support', ascending=False).head(10).to_string())